### Applying Changes

"""
Syntax: diff -u old_file new_file > change.diff
The greater than sign redirects the output of the diff command to a file.

We're generating a file called change.diff with the contents of diff-u command.
By using the -u flag,we include more context which helps the person reading the file understand
what's going on with the change.
The generated file is usually referred to as a diff file or sometimes a patch file.
It includes all the changes between the old file and the new one, plus the additional context needed to understand
the changes and to apply those changes back to the original file. 

Patch command takes a file generated by diff and applies the changes to the original file
"""

# cat cpu_usage1.py

#!/usr/bin/env python3
import psutil

def check_cpu_usage(percent):
    usage = psutil.cpu_percent()
    return usage < percent

if not check_cpu_usage(75):
    print("ERROR! CPU is overloaded")
else:
    print("Everything ok")



# cat cpu_usage2.py

#!/usr/bin/env python3
import psutil

def check_cpu_usage(percent):
    usage = psutil.cpu_percent(1)
    print("DEBUG: usage: {}".format(usage))
    return usage < percent

if not check_cpu_usage(75):
    print("ERROR! CPU is overloaded")
else:
    print("Everything ok")



# diff -u cpu_usage1.py cpu_usage2.py > cpu_usage.diff
# cat cpu_usage.diff
"""
--- cpu_usage1.py	2023-10-26 18:29:37.128497843 +0200
+++ cpu_usage2.py	2023-10-26 18:01:33.763549774 +0200
@@ -2,10 +2,11 @@
 import psutil
 
 def check_cpu_usage(percent):
-    usage = psutil.cpu_percent()
+    usage = psutil.cpu_percent(1)
+    print("DEBUG: usage: {}".format(usage))
     return usage < percent
 
 if not check_cpu_usage(75):
     print("ERROR! CPU is overloaded")
 else:
-    print("Everything ok")
+    print("Everything ok")
\ No newline at end of file
"""

# patch cpu_usage1.py < cpu_usage.diff
"""patching file cpu_usage1.py
"""

"""We'll pass the name of the file that we want to patch in this case, cpu_usage.py, as the first parameter to the command
and then we'll provide the diff file through standard input. will use the less than symbol to redirect the contents of the file to standard input"""

